### ISSUE TITLE
Surge Deployer

### ISSUE THREAD

**Issue by joshrowley** [carrot/ship#69]
I've never used this, but someone showed it to me today and said good things. Could be a good deployer for this project if someone is interested in implementing.

https://surge.sh/
https://github.com/sintaxi/surge

**Comment by kylemac** [comment]
surge is pretty cool. it's less featured than netlify, but that's by design. 

as for a deployer, i think surge kind of circumvents the need for ship because it's just a CLI that ships static files. no JS api and wack test coverage has always made me a little weary - https://github.com/sintaxi/surge/blob/master/test/basic.js 

we'll keep put this in the backlog. there's been some more talk about giving ship a fresh coat of paint (again) too.

**Comment by jenius** [comment]
This looks pretty decent. The benefit of integrating it with ship is less global install necessities, more consistency with the options, and potential api-based integration into other things, rather than being stuck always using their cli deployer. I'd be down for adding this and checking it out.
